# Generated by Django 5.1.2 on 2024-10-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('train_types', '0002_alter_traintype_type_name'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='train',
            name='stations',
            field=models.ManyToManyField(related_name='trains', to='stations.station', verbose_name='Станции'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train_types.traintype', verbose_name='Тип поезда'),
        ),
    ]
