version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: railway_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
