# Generated by Django 5.1.2 on 2024-10-11 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_directory', '0001_initial'),
        ('routes', '0001_initial'),
        ('stations', '0002_alter_station_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='arrival_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='crew',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crew_directory.crewdirectory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='owner_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_routes', to='stations.station'),
            preserve_default=False,
        ),
    ]
