# Generated by Django 5.1.2 on 2024-10-11 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tax_id', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен состоять из 12 цифр.', regex='^\\d{12}$')], verbose_name='ИНН')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addresses.address', verbose_name='Адрес')),
            ],
        ),
    ]
