# Generated by Django 5.1.2 on 2024-10-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewdirectory',
            name='crew_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Справочник бригад'),
        ),
    ]
